import { Info } from 'lucide-react'
import './Disclaimer.css'

// Reusable AI-transparency + medical-disclaimer notice.
// Keeps the "who generated this and how reliable is it" context visible
// without interrupting the main flow.
export default function Disclaimer({ compact = false }) {
  return (
    <div className={`disclaimer ${compact ? 'disclaimer--compact' : ''}`}>
      <Info size={16} className="disclaimer__icon" />
      <p className="disclaimer__text">
        CalmCare AI gives general health information generated by AI (Groq, with Gemini as
        backup) — it is not a medical diagnosis and hasn't been reviewed by a doctor. AI
        responses can be incomplete or wrong. Always confirm anything important with a
        qualified healthcare professional, and call your local emergency number for urgent
        symptoms.
      </p>
    </div>
  )
}
